### ISSUE TITLE
Password keeps loading forever

### ISSUE THREAD

**Issue by fjcaetano** [ehazlett/locksmith#17]
On locksmith.io all passwords keep "loading" forever and never show. It's happening on both my accounts.

**Comment by ehazlett** [comment]
I haven't seen any errors from Sentry.   There was an issue I was trying to track down with encodings -- if you are using any extended characters in the encryption key (the one you are prompted for when logging in) try using a different key and then create a new credential and see if it loads.

**Comment by fjcaetano** [comment]
It worked for new credentials, but the old passwords still doesn't load.

**Comment by ehazlett** [comment]
Can you tell me the characters you were using? Don't put the whole key just
the extended chars.

Thanks.

**Comment by meskarune** [comment]
I wanted to let you know I am also having this problem. I tried different operating systems and browsers as well. I have the following extended characters in my key: 

|#"<

**Comment by ehazlett** [comment]
@meskarune thx for letting me know the characters.  i'll see what i can do.

**Comment by meskarune** [comment]
Thanks for looking into this. I can't access any of my passwords atm, it just says "loading". I had to reset some of them to get into the accounts. If you need any other information, please let me know.

**Comment by meskarune** [comment]
I think you fixed this issue a while back, so you may be able to set it as closed.
